name: "Cosmic Dependency Detection Action"
description: "Action using the dependency-submission-toolkit"
inputs:
  token:
    description: "GitHub Personal Access Token (PAT). Defaults to PAT provided by Action runner"
    required: false
    default: ${{ github.token }}
  cosmic-package-directory:
    description: "Cosmic package directory (directory with Cosmic *.pkl files)"
    required: true
    default: ${{ github.workspace }}
  package-module-filename:
    description: "The name of the package module file"
    required: true
    default: ".package.pkl"
runs:
  using: node20
  main: dist/index.js
